name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: RomainRG31/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ waka_4e6f48a0-370a-40c3-b8f1-4e1a5de666cc }}
          GH_TOKEN: ${{ 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 }}
          SHOW_COMMIT: "true"
          SHOW_LANGUAGE: "true"
          SHOW_DAYS_OF_WEEK: "true"
          SHOW_OS: "true"
